### ISSUE TITLE
The `<ReposList>` component and Netlify function

### ISSUE THREAD

**Issue by JasonEtco** [JasonEtco/jasonet.co#19]
![image](https://user-images.githubusercontent.com/10660468/52129159-d6624580-2604-11e9-8215-1531a7b687e8.png)

* React components
  * [`<ReposList>`](https://github.com/JasonEtco/jasonet.co/blob/master/src/components/ReposList.js)
  * [`<Repo>`](https://github.com/JasonEtco/jasonet.co/blob/master/src/components/Repo.js)
* [Netlify Function](https://github.com/JasonEtco/jasonet.co/blob/master/functions/get-repos.js)
  * [GraphQL query](https://github.com/JasonEtco/jasonet.co/blob/2d8688628f4673477e9c35d071a5cf2f7b6fbeaf/functions/get-repos.js#L3-L21)
  * [Including a PAT](https://github.com/JasonEtco/jasonet.co/blob/2d8688628f4673477e9c35d071a5cf2f7b6fbeaf/functions/get-repos.js#L31)

**Comment by johnletey** [comment]
@JasonEtco It'd also be great to know how to do this _without_ Netlify functions

**Comment by Jerwins** [comment]
How do I make use of this? is there a specific guide to achieve this?

**Comment by JasonEtco** [comment]
Nope - not yet, that's what this proposed blog post would be!

**Comment by Jerwins** [comment]
I see. I keep getting this every time I let that function run. 

> Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot read property 'viewer' of undefined","stack":["TypeError: Cannot read property 'viewer' of undefined","    at Runtime.handler (/var/task/get-repos.js:65:30)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)"]}

**Comment by JasonEtco** [comment]
It’s not meant to be lifted out of this repo and used separately, so it won’t work without some other setup. Hang tight for the blog post ❤️
